config/routes.rb
Rails.application.routes.draw do

  get '/actors', to: 'actors#index'
  get 'actors/new', to: 'actors#new', as: 'new_actor'
  post '/actors', to: 'actors#create'

end

app/models/actor.rb
class Actor < ApplicationRecord
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/actors_controller.rb
class ActorsController < ApplicationController

    def index
        @actors = Actor.all
    end

    def new
        @actor = Actor.new
    end

    def create
        actor = Actor.new(artist_params)
        if actor.save
            redirect_to actors_path
        else
            render :new
        end
    end

    def artist_params
        params.require(:actor).permit(:death_place, :death_date, :image_url, :birth_place, :birth_date, :bio, :name, :alive)
    end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/helpers/actors_helper.rb
module ActorsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/actors/index.html.erb
<h1>Actor</h1>
<p><%= link_to  "Crear Actor", new_actor_path %></p>
<%@actors.each do |actor|%>
<img src="<%=actor.image_url%>" width="128" height="188">
<h3><%=actor.name%></h3>
<p> <%=actor.bio%> </p>
<p><strong>Born Date: </strong><%=actor.birth_date%></p>
<p><strong>Born Place: </strong><%=actor.birth_place%></p>
<% if actor.alive == false %>
<p><strong>Death Date: </strong><%=actor.death_date%></p>
<p><strong>Death Place: </strong><%=actor.death_place%></p>
<%end%>
<hr>
<%end%>

app/views/actors/new.html.erb
<h1>Crear un nuevo Actor</h1>

<%= form_for @actor do |f| %>
<%= f.label :name %>
<%= f.text_field :name %>
<br>
<%= f.label :image_url %>
<%= f.text_field :image_url %>
<br>
<%= f.label :bio %>
<%= f.text_field :bio %>
<br>
<%= f.label :alive? %>
<%= f.check_box :alive %>
<br>
<%= f.label :birth_date %>
<%= f.text_field :birth_date %>
<br>
<%= f.label :birth_place %>
<%= f.text_field :birth_place %>
<br>
<%= f.label :death_date %>
<%= f.text_field :death_date %>
<br>
<%= f.label :death_place %>
<%= f.text_field :death_place %>
<br>
<%= f.submit %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>C03jh9ir6</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>